//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.googlecode.androidannotations.maveneclipse;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.res.Resources;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.TextView;
import com.googlecode.androidannotations.maveneclipse.R.id;
import com.googlecode.androidannotations.maveneclipse.R.layout;
import com.googlecode.androidannotations.maveneclipse.R.string;

public final class HelloAndroidActivity_
    extends HelloAndroidActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.main);
    }

    private void init_(Bundle savedInstanceState) {
        Resources resources_ = this.getResources();
        hello = resources_.getString(string.hello);
    }

    private void afterSetContentView_() {
        helloTextView = ((TextView) findViewById(id.helloTextView));
        initViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static HelloAndroidActivity_.IntentBuilder_ intent(Context context) {
        return new HelloAndroidActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, HelloAndroidActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public HelloAndroidActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
